// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: thorchain/v1/common/common.proto

package common

import (
	cosmossdk_io_math "cosmossdk.io/math"
	_ "github.com/gogo/protobuf/gogoproto"
)

type Coin struct {
	Asset    Asset                  `json:"asset"`
	Amount   cosmossdk_io_math.Uint `json:"amount"`
	Decimals int64                  `json:"decimals,omitempty"`
}

type Coins []Coin

// NewCoin return a new instance of Coin
func NewCoin(asset Asset, amount cosmossdk_io_math.Uint) Coin {
	return Coin{
		Asset:  asset,
		Amount: amount,
	}
}
