// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: penumbra/core/component/ibc/v1/ibc.proto

package ibcv1

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	proto "github.com/cosmos/gogoproto/proto"
	types1 "github.com/cosmos/ibc-go/v8/modules/core/02-client/types"
	v11 "github.com/strangelove-ventures/interchaintest/v8/chain/penumbra/core/asset/v1"
	v12 "github.com/strangelove-ventures/interchaintest/v8/chain/penumbra/core/keys/v1"
	v1 "github.com/strangelove-ventures/interchaintest/v8/chain/penumbra/core/num/v1"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type IbcRelay struct {
	RawAction *types.Any `protobuf:"bytes,1,opt,name=raw_action,json=rawAction,proto3" json:"raw_action,omitempty"`
}

func (m *IbcRelay) Reset()         { *m = IbcRelay{} }
func (m *IbcRelay) String() string { return proto.CompactTextString(m) }
func (*IbcRelay) ProtoMessage()    {}
func (*IbcRelay) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bed36356ff7581e, []int{0}
}
func (m *IbcRelay) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IbcRelay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IbcRelay.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IbcRelay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IbcRelay.Merge(m, src)
}
func (m *IbcRelay) XXX_Size() int {
	return m.Size()
}
func (m *IbcRelay) XXX_DiscardUnknown() {
	xxx_messageInfo_IbcRelay.DiscardUnknown(m)
}

var xxx_messageInfo_IbcRelay proto.InternalMessageInfo

func (m *IbcRelay) GetRawAction() *types.Any {
	if m != nil {
		return m.RawAction
	}
	return nil
}

// FungibleTokenPacketData defines a struct for the packet payload
// See FungibleTokenPacketData spec:
// https://github.com/cosmos/ibc/tree/master/spec/app/ics-020-fungible-token-transfer#data-structures
type FungibleTokenPacketData struct {
	// the token denomination to be transferred
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	// the token amount to be transferred
	Amount string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// the return address
	Sender string `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	// the recipient address on the destination chain
	Receiver string `protobuf:"bytes,4,opt,name=receiver,proto3" json:"receiver,omitempty"`
	// optional memo
	Memo string `protobuf:"bytes,5,opt,name=memo,proto3" json:"memo,omitempty"`
}

func (m *FungibleTokenPacketData) Reset()         { *m = FungibleTokenPacketData{} }
func (m *FungibleTokenPacketData) String() string { return proto.CompactTextString(m) }
func (*FungibleTokenPacketData) ProtoMessage()    {}
func (*FungibleTokenPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bed36356ff7581e, []int{1}
}
func (m *FungibleTokenPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FungibleTokenPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FungibleTokenPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FungibleTokenPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FungibleTokenPacketData.Merge(m, src)
}
func (m *FungibleTokenPacketData) XXX_Size() int {
	return m.Size()
}
func (m *FungibleTokenPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_FungibleTokenPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_FungibleTokenPacketData proto.InternalMessageInfo

func (m *FungibleTokenPacketData) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *FungibleTokenPacketData) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *FungibleTokenPacketData) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *FungibleTokenPacketData) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *FungibleTokenPacketData) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

// A Penumbra transaction action requesting an ICS20 transfer.
type Ics20Withdrawal struct {
	Amount *v1.Amount `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Denom  *v11.Denom `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	// the address on the destination chain to send the transfer to
	DestinationChainAddress string `protobuf:"bytes,3,opt,name=destination_chain_address,json=destinationChainAddress,proto3" json:"destination_chain_address,omitempty"`
	// a "sender" penumbra address to use to return funds from this withdrawal.
	// this should be an ephemeral address
	ReturnAddress *v12.Address `protobuf:"bytes,4,opt,name=return_address,json=returnAddress,proto3" json:"return_address,omitempty"`
	// The height on the counterparty chain at which this transfer expires, and
	// funds are sent back to the return address.
	TimeoutHeight *types1.Height `protobuf:"bytes,5,opt,name=timeout_height,json=timeoutHeight,proto3" json:"timeout_height,omitempty"`
	// the timestamp at which this transfer expires.
	TimeoutTime uint64 `protobuf:"varint,6,opt,name=timeout_time,json=timeoutTime,proto3" json:"timeout_time,omitempty"`
	// the source channel used for the withdrawal
	SourceChannel string `protobuf:"bytes,7,opt,name=source_channel,json=sourceChannel,proto3" json:"source_channel,omitempty"`
}

func (m *Ics20Withdrawal) Reset()         { *m = Ics20Withdrawal{} }
func (m *Ics20Withdrawal) String() string { return proto.CompactTextString(m) }
func (*Ics20Withdrawal) ProtoMessage()    {}
func (*Ics20Withdrawal) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bed36356ff7581e, []int{2}
}
func (m *Ics20Withdrawal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Ics20Withdrawal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Ics20Withdrawal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Ics20Withdrawal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ics20Withdrawal.Merge(m, src)
}
func (m *Ics20Withdrawal) XXX_Size() int {
	return m.Size()
}
func (m *Ics20Withdrawal) XXX_DiscardUnknown() {
	xxx_messageInfo_Ics20Withdrawal.DiscardUnknown(m)
}

var xxx_messageInfo_Ics20Withdrawal proto.InternalMessageInfo

func (m *Ics20Withdrawal) GetAmount() *v1.Amount {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *Ics20Withdrawal) GetDenom() *v11.Denom {
	if m != nil {
		return m.Denom
	}
	return nil
}

func (m *Ics20Withdrawal) GetDestinationChainAddress() string {
	if m != nil {
		return m.DestinationChainAddress
	}
	return ""
}

func (m *Ics20Withdrawal) GetReturnAddress() *v12.Address {
	if m != nil {
		return m.ReturnAddress
	}
	return nil
}

func (m *Ics20Withdrawal) GetTimeoutHeight() *types1.Height {
	if m != nil {
		return m.TimeoutHeight
	}
	return nil
}

func (m *Ics20Withdrawal) GetTimeoutTime() uint64 {
	if m != nil {
		return m.TimeoutTime
	}
	return 0
}

func (m *Ics20Withdrawal) GetSourceChannel() string {
	if m != nil {
		return m.SourceChannel
	}
	return ""
}

type ClientData struct {
	ClientId        string     `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientState     *types.Any `protobuf:"bytes,2,opt,name=client_state,json=clientState,proto3" json:"client_state,omitempty"`
	ProcessedTime   string     `protobuf:"bytes,3,opt,name=processed_time,json=processedTime,proto3" json:"processed_time,omitempty"`
	ProcessedHeight uint64     `protobuf:"varint,4,opt,name=processed_height,json=processedHeight,proto3" json:"processed_height,omitempty"`
}

func (m *ClientData) Reset()         { *m = ClientData{} }
func (m *ClientData) String() string { return proto.CompactTextString(m) }
func (*ClientData) ProtoMessage()    {}
func (*ClientData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bed36356ff7581e, []int{3}
}
func (m *ClientData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClientData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClientData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClientData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientData.Merge(m, src)
}
func (m *ClientData) XXX_Size() int {
	return m.Size()
}
func (m *ClientData) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientData.DiscardUnknown(m)
}

var xxx_messageInfo_ClientData proto.InternalMessageInfo

func (m *ClientData) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *ClientData) GetClientState() *types.Any {
	if m != nil {
		return m.ClientState
	}
	return nil
}

func (m *ClientData) GetProcessedTime() string {
	if m != nil {
		return m.ProcessedTime
	}
	return ""
}

func (m *ClientData) GetProcessedHeight() uint64 {
	if m != nil {
		return m.ProcessedHeight
	}
	return 0
}

type ClientCounter struct {
	Counter uint64 `protobuf:"varint,1,opt,name=counter,proto3" json:"counter,omitempty"`
}

func (m *ClientCounter) Reset()         { *m = ClientCounter{} }
func (m *ClientCounter) String() string { return proto.CompactTextString(m) }
func (*ClientCounter) ProtoMessage()    {}
func (*ClientCounter) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bed36356ff7581e, []int{4}
}
func (m *ClientCounter) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClientCounter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClientCounter.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClientCounter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientCounter.Merge(m, src)
}
func (m *ClientCounter) XXX_Size() int {
	return m.Size()
}
func (m *ClientCounter) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientCounter.DiscardUnknown(m)
}

var xxx_messageInfo_ClientCounter proto.InternalMessageInfo

func (m *ClientCounter) GetCounter() uint64 {
	if m != nil {
		return m.Counter
	}
	return 0
}

type ConsensusState struct {
	ConsensusState *types.Any `protobuf:"bytes,1,opt,name=consensus_state,json=consensusState,proto3" json:"consensus_state,omitempty"`
}

func (m *ConsensusState) Reset()         { *m = ConsensusState{} }
func (m *ConsensusState) String() string { return proto.CompactTextString(m) }
func (*ConsensusState) ProtoMessage()    {}
func (*ConsensusState) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bed36356ff7581e, []int{5}
}
func (m *ConsensusState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConsensusState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConsensusState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConsensusState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusState.Merge(m, src)
}
func (m *ConsensusState) XXX_Size() int {
	return m.Size()
}
func (m *ConsensusState) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusState.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusState proto.InternalMessageInfo

func (m *ConsensusState) GetConsensusState() *types.Any {
	if m != nil {
		return m.ConsensusState
	}
	return nil
}

type VerifiedHeights struct {
	Heights []*types1.Height `protobuf:"bytes,1,rep,name=heights,proto3" json:"heights,omitempty"`
}

func (m *VerifiedHeights) Reset()         { *m = VerifiedHeights{} }
func (m *VerifiedHeights) String() string { return proto.CompactTextString(m) }
func (*VerifiedHeights) ProtoMessage()    {}
func (*VerifiedHeights) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bed36356ff7581e, []int{6}
}
func (m *VerifiedHeights) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VerifiedHeights) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VerifiedHeights.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VerifiedHeights) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifiedHeights.Merge(m, src)
}
func (m *VerifiedHeights) XXX_Size() int {
	return m.Size()
}
func (m *VerifiedHeights) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifiedHeights.DiscardUnknown(m)
}

var xxx_messageInfo_VerifiedHeights proto.InternalMessageInfo

func (m *VerifiedHeights) GetHeights() []*types1.Height {
	if m != nil {
		return m.Heights
	}
	return nil
}

type ConnectionCounter struct {
	Counter uint64 `protobuf:"varint,1,opt,name=counter,proto3" json:"counter,omitempty"`
}

func (m *ConnectionCounter) Reset()         { *m = ConnectionCounter{} }
func (m *ConnectionCounter) String() string { return proto.CompactTextString(m) }
func (*ConnectionCounter) ProtoMessage()    {}
func (*ConnectionCounter) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bed36356ff7581e, []int{7}
}
func (m *ConnectionCounter) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConnectionCounter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConnectionCounter.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConnectionCounter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionCounter.Merge(m, src)
}
func (m *ConnectionCounter) XXX_Size() int {
	return m.Size()
}
func (m *ConnectionCounter) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionCounter.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionCounter proto.InternalMessageInfo

func (m *ConnectionCounter) GetCounter() uint64 {
	if m != nil {
		return m.Counter
	}
	return 0
}

type ClientConnections struct {
	Connections []string `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"`
}

func (m *ClientConnections) Reset()         { *m = ClientConnections{} }
func (m *ClientConnections) String() string { return proto.CompactTextString(m) }
func (*ClientConnections) ProtoMessage()    {}
func (*ClientConnections) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bed36356ff7581e, []int{8}
}
func (m *ClientConnections) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClientConnections) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClientConnections.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClientConnections) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientConnections.Merge(m, src)
}
func (m *ClientConnections) XXX_Size() int {
	return m.Size()
}
func (m *ClientConnections) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientConnections.DiscardUnknown(m)
}

var xxx_messageInfo_ClientConnections proto.InternalMessageInfo

func (m *ClientConnections) GetConnections() []string {
	if m != nil {
		return m.Connections
	}
	return nil
}

// IBC configuration data.
type IbcParameters struct {
	// Whether IBC (forming connections, processing IBC packets) is enabled.
	IbcEnabled bool `protobuf:"varint,1,opt,name=ibc_enabled,json=ibcEnabled,proto3" json:"ibc_enabled,omitempty"`
	// Whether inbound ICS-20 transfers are enabled
	InboundIcs20TransfersEnabled bool `protobuf:"varint,2,opt,name=inbound_ics20_transfers_enabled,json=inboundIcs20TransfersEnabled,proto3" json:"inbound_ics20_transfers_enabled,omitempty"`
	// Whether outbound ICS-20 transfers are enabled
	OutboundIcs20TransfersEnabled bool `protobuf:"varint,3,opt,name=outbound_ics20_transfers_enabled,json=outboundIcs20TransfersEnabled,proto3" json:"outbound_ics20_transfers_enabled,omitempty"`
}

func (m *IbcParameters) Reset()         { *m = IbcParameters{} }
func (m *IbcParameters) String() string { return proto.CompactTextString(m) }
func (*IbcParameters) ProtoMessage()    {}
func (*IbcParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bed36356ff7581e, []int{9}
}
func (m *IbcParameters) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IbcParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IbcParameters.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IbcParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IbcParameters.Merge(m, src)
}
func (m *IbcParameters) XXX_Size() int {
	return m.Size()
}
func (m *IbcParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_IbcParameters.DiscardUnknown(m)
}

var xxx_messageInfo_IbcParameters proto.InternalMessageInfo

func (m *IbcParameters) GetIbcEnabled() bool {
	if m != nil {
		return m.IbcEnabled
	}
	return false
}

func (m *IbcParameters) GetInboundIcs20TransfersEnabled() bool {
	if m != nil {
		return m.InboundIcs20TransfersEnabled
	}
	return false
}

func (m *IbcParameters) GetOutboundIcs20TransfersEnabled() bool {
	if m != nil {
		return m.OutboundIcs20TransfersEnabled
	}
	return false
}

// IBC genesis state.
type GenesisContent struct {
	// IBC parameters.
	IbcParams *IbcParameters `protobuf:"bytes,1,opt,name=ibc_params,json=ibcParams,proto3" json:"ibc_params,omitempty"`
}

func (m *GenesisContent) Reset()         { *m = GenesisContent{} }
func (m *GenesisContent) String() string { return proto.CompactTextString(m) }
func (*GenesisContent) ProtoMessage()    {}
func (*GenesisContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bed36356ff7581e, []int{10}
}
func (m *GenesisContent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisContent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisContent.Merge(m, src)
}
func (m *GenesisContent) XXX_Size() int {
	return m.Size()
}
func (m *GenesisContent) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisContent.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisContent proto.InternalMessageInfo

func (m *GenesisContent) GetIbcParams() *IbcParameters {
	if m != nil {
		return m.IbcParams
	}
	return nil
}

func init() {
	proto.RegisterType((*IbcRelay)(nil), "penumbra.core.component.ibc.v1.IbcRelay")
	proto.RegisterType((*FungibleTokenPacketData)(nil), "penumbra.core.component.ibc.v1.FungibleTokenPacketData")
	proto.RegisterType((*Ics20Withdrawal)(nil), "penumbra.core.component.ibc.v1.Ics20Withdrawal")
	proto.RegisterType((*ClientData)(nil), "penumbra.core.component.ibc.v1.ClientData")
	proto.RegisterType((*ClientCounter)(nil), "penumbra.core.component.ibc.v1.ClientCounter")
	proto.RegisterType((*ConsensusState)(nil), "penumbra.core.component.ibc.v1.ConsensusState")
	proto.RegisterType((*VerifiedHeights)(nil), "penumbra.core.component.ibc.v1.VerifiedHeights")
	proto.RegisterType((*ConnectionCounter)(nil), "penumbra.core.component.ibc.v1.ConnectionCounter")
	proto.RegisterType((*ClientConnections)(nil), "penumbra.core.component.ibc.v1.ClientConnections")
	proto.RegisterType((*IbcParameters)(nil), "penumbra.core.component.ibc.v1.IbcParameters")
	proto.RegisterType((*GenesisContent)(nil), "penumbra.core.component.ibc.v1.GenesisContent")
}

func init() {
	proto.RegisterFile("penumbra/core/component/ibc/v1/ibc.proto", fileDescriptor_2bed36356ff7581e)
}

var fileDescriptor_2bed36356ff7581e = []byte{
	// 952 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x95, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xc7, 0xd7, 0x69, 0xb6, 0x1f, 0x93, 0x4d, 0xca, 0x5a, 0x2b, 0x36, 0x5b, 0x76, 0xdd, 0x60,
	0x09, 0xa9, 0x8b, 0x54, 0x1b, 0xb7, 0x8b, 0x40, 0x41, 0x08, 0xb5, 0xde, 0x52, 0x22, 0x81, 0x88,
	0x4c, 0x55, 0x24, 0x14, 0x11, 0x8d, 0xc7, 0xa7, 0xe9, 0xa8, 0xf1, 0x4c, 0x34, 0x33, 0x76, 0xd5,
	0x77, 0x40, 0x82, 0x67, 0xe0, 0x92, 0x6b, 0x1e, 0x00, 0xee, 0x10, 0x57, 0x7b, 0xc9, 0x25, 0x6a,
	0xef, 0x78, 0x0a, 0x34, 0x33, 0x76, 0xba, 0x59, 0xad, 0xd2, 0x9b, 0xd8, 0xe7, 0xcc, 0xef, 0x9c,
	0xf9, 0x9f, 0x33, 0x67, 0x1c, 0xb4, 0x33, 0x03, 0x56, 0xe4, 0xa9, 0xc0, 0x21, 0xe1, 0x02, 0x42,
	0xc2, 0xf3, 0x19, 0x67, 0xc0, 0x54, 0x48, 0x53, 0x12, 0x96, 0x91, 0x7e, 0x04, 0x33, 0xc1, 0x15,
	0x77, 0xbd, 0x9a, 0x0c, 0x34, 0x19, 0xcc, 0xc9, 0x40, 0x23, 0x65, 0xb4, 0xf5, 0x64, 0xc2, 0xf9,
	0x64, 0x0a, 0xa1, 0xa1, 0xd3, 0xe2, 0x2c, 0xc4, 0xec, 0xca, 0x86, 0x6e, 0x6d, 0xeb, 0x64, 0x36,
	0xff, 0x94, 0xea, 0xe4, 0x65, 0x54, 0xbd, 0x55, 0x80, 0xbf, 0xa8, 0x02, 0x4b, 0x09, 0x06, 0x32,
	0x2f, 0x15, 0xd3, 0x5b, 0x64, 0x2e, 0xe0, 0x4a, 0x6a, 0x44, 0x3f, 0x2b, 0xc2, 0x5b, 0x24, 0x58,
	0x91, 0x6b, 0x80, 0x15, 0xb9, 0x5d, 0xf7, 0xbf, 0x40, 0xeb, 0x83, 0x94, 0x24, 0x30, 0xc5, 0x57,
	0xee, 0x3e, 0x42, 0x02, 0x5f, 0x8e, 0x31, 0x51, 0x94, 0xb3, 0xae, 0xd3, 0x73, 0x76, 0x5a, 0x7b,
	0x8f, 0x02, 0x5b, 0x42, 0x50, 0x97, 0x10, 0x1c, 0xb0, 0xab, 0x64, 0x43, 0xe0, 0xcb, 0x03, 0x83,
	0xf9, 0x3f, 0x3b, 0xe8, 0xf1, 0x97, 0x05, 0x9b, 0xd0, 0x74, 0x0a, 0x27, 0xfc, 0x02, 0xd8, 0x10,
	0x93, 0x0b, 0x50, 0x2f, 0xb1, 0xc2, 0xee, 0x23, 0x74, 0x3f, 0x03, 0xc6, 0x73, 0x93, 0x6b, 0x23,
	0xb1, 0x86, 0xfb, 0x2e, 0x5a, 0xc5, 0x39, 0x2f, 0x98, 0xea, 0x36, 0x8c, 0xbb, 0xb2, 0xb4, 0x5f,
	0x02, 0xcb, 0x40, 0x74, 0x57, 0xac, 0xdf, 0x5a, 0xee, 0x16, 0x5a, 0x17, 0x40, 0x80, 0x96, 0x20,
	0xba, 0x4d, 0xb3, 0x32, 0xb7, 0x5d, 0x17, 0x35, 0x73, 0xc8, 0x79, 0xf7, 0xbe, 0xf1, 0x9b, 0x77,
	0xff, 0xa7, 0x15, 0xb4, 0x39, 0x20, 0x72, 0xef, 0xa3, 0xef, 0xa9, 0x3a, 0xcf, 0x04, 0xbe, 0xc4,
	0x53, 0xf7, 0xc5, 0x7c, 0x4f, 0x5b, 0xd6, 0xd3, 0x60, 0xf1, 0xe4, 0x74, 0x43, 0xca, 0x28, 0x38,
	0x30, 0xcc, 0x5c, 0xd1, 0x7e, 0xad, 0xbf, 0x61, 0x82, 0x9e, 0xbd, 0x11, 0x64, 0x4f, 0xa2, 0x8c,
	0x82, 0x97, 0x1a, 0xaa, 0xcb, 0xeb, 0xa3, 0x27, 0x19, 0x48, 0x45, 0x19, 0xd6, 0xfd, 0x19, 0x93,
	0x73, 0x4c, 0xd9, 0x18, 0x67, 0x99, 0x00, 0x29, 0xab, 0xca, 0x1e, 0xbf, 0x06, 0xc4, 0x7a, 0xfd,
	0xc0, 0x2e, 0xbb, 0x47, 0xa8, 0x23, 0x40, 0x15, 0xe2, 0x36, 0xa0, 0x69, 0x76, 0xf6, 0xde, 0xd8,
	0xd9, 0x1c, 0xb0, 0xd6, 0x6b, 0xa9, 0xa4, 0x6d, 0xa3, 0xea, 0x34, 0x07, 0xa8, 0xa3, 0x68, 0x0e,
	0xbc, 0x50, 0xe3, 0x73, 0xa0, 0x93, 0x73, 0x65, 0xfa, 0xd3, 0xda, 0xdb, 0x32, 0x73, 0x69, 0x47,
	0xd5, 0x8e, 0x5a, 0x19, 0x05, 0x5f, 0x19, 0x22, 0x69, 0x57, 0x11, 0xd6, 0x74, 0xdf, 0x47, 0x0f,
	0xea, 0x14, 0xfa, 0xd9, 0x5d, 0xed, 0x39, 0x3b, 0xcd, 0xa4, 0x55, 0xf9, 0x4e, 0x68, 0x0e, 0xee,
	0x07, 0xa8, 0x23, 0x79, 0x21, 0x08, 0xe8, 0x1a, 0x19, 0x83, 0x69, 0x77, 0xcd, 0x54, 0xd7, 0xb6,
	0xde, 0xd8, 0x3a, 0xfd, 0xdf, 0x1d, 0x84, 0x62, 0xb3, 0x9b, 0x99, 0x89, 0xf7, 0xd0, 0x86, 0xdd,
	0x7b, 0x4c, 0xb3, 0x6a, 0x2e, 0xd6, 0xad, 0x63, 0x90, 0xb9, 0x9f, 0xa0, 0x07, 0xd5, 0xa2, 0x54,
	0x58, 0x41, 0xd5, 0xf7, 0xb7, 0xcf, 0x60, 0xcb, 0x92, 0xdf, 0x69, 0x50, 0x6b, 0x99, 0x09, 0x4e,
	0x40, 0x4a, 0xc8, 0xac, 0x60, 0xdb, 0xe9, 0xf6, 0xdc, 0x6b, 0x24, 0x3f, 0x47, 0xef, 0xdc, 0x62,
	0x55, 0x6b, 0x9a, 0xa6, 0xb2, 0xcd, 0xb9, 0xdf, 0x36, 0xc0, 0x7f, 0x8e, 0xda, 0x56, 0x75, 0xac,
	0x47, 0x01, 0x84, 0xdb, 0x45, 0x6b, 0xc4, 0xbe, 0x1a, 0xd9, 0xcd, 0xa4, 0x36, 0xfd, 0x6f, 0x51,
	0x27, 0xe6, 0x4c, 0x02, 0x93, 0x85, 0xb4, 0x72, 0x3e, 0x47, 0x9b, 0xa4, 0xf6, 0x54, 0xa5, 0x2c,
	0xbb, 0x4e, 0x1d, 0xb2, 0x10, 0xee, 0x1f, 0xa3, 0xcd, 0x53, 0x10, 0xf4, 0x8c, 0xd6, 0x6a, 0xa4,
	0xfb, 0x02, 0xad, 0x59, 0xbd, 0xb2, 0xeb, 0xf4, 0x56, 0xee, 0x38, 0xcb, 0x1a, 0xf5, 0x77, 0xd1,
	0xc3, 0x98, 0x33, 0x06, 0xe6, 0xaa, 0xde, 0x5d, 0xc8, 0xc7, 0xe8, 0x61, 0x5d, 0x73, 0x1d, 0x24,
	0xdd, 0x1e, 0x6a, 0x91, 0x5b, 0xd3, 0xec, 0xbe, 0x91, 0xbc, 0xee, 0xf2, 0xff, 0x70, 0x50, 0x7b,
	0x90, 0x92, 0x21, 0x16, 0x38, 0x07, 0x05, 0x42, 0xba, 0xdb, 0xa8, 0x45, 0x53, 0x32, 0x06, 0x86,
	0xd3, 0x29, 0xd8, 0x63, 0x5e, 0x4f, 0x10, 0x4d, 0xc9, 0x91, 0xf5, 0xb8, 0x47, 0x68, 0x9b, 0xb2,
	0x94, 0x17, 0x2c, 0x1b, 0x53, 0x7d, 0x55, 0xc7, 0x4a, 0x60, 0x26, 0xcf, 0x40, 0xc8, 0x79, 0x50,
	0xc3, 0x04, 0x3d, 0xad, 0x30, 0x73, 0xa1, 0x4f, 0x6a, 0xa8, 0x4e, 0x73, 0x8c, 0x7a, 0xbc, 0x50,
	0xcb, 0xf3, 0xac, 0x98, 0x3c, 0xcf, 0x6a, 0xee, 0xad, 0x89, 0xfc, 0x1f, 0x51, 0xe7, 0x18, 0x18,
	0x48, 0x2a, 0x63, 0xce, 0x14, 0x30, 0xe5, 0x7e, 0x8d, 0xb4, 0xde, 0xf1, 0x4c, 0x17, 0x25, 0xab,
	0xd3, 0xdb, 0x0d, 0x96, 0x7f, 0xef, 0x83, 0x85, 0x2e, 0x24, 0x1b, 0xb4, 0x32, 0xe5, 0xe1, 0x9f,
	0x8d, 0xbf, 0xae, 0x3d, 0xe7, 0xd5, 0xb5, 0xe7, 0xfc, 0x7b, 0xed, 0x39, 0xbf, 0xdc, 0x78, 0xf7,
	0x5e, 0xdd, 0x78, 0xf7, 0xfe, 0xb9, 0xf1, 0xee, 0x21, 0x9f, 0xf0, 0xfc, 0x8e, 0xbc, 0x87, 0xfa,
	0x1b, 0x3d, 0xd4, 0x13, 0x33, 0x74, 0x7e, 0x18, 0x4d, 0xa8, 0x3a, 0x2f, 0x52, 0x0d, 0x85, 0x52,
	0x97, 0x3b, 0x81, 0x29, 0x2f, 0x61, 0xb7, 0x04, 0xa6, 0x0a, 0x01, 0x32, 0xa4, 0xfa, 0x2c, 0xcd,
	0x67, 0x47, 0x81, 0x54, 0x61, 0xf9, 0x69, 0x68, 0x8c, 0x70, 0xf9, 0xbf, 0xda, 0x67, 0x34, 0x25,
	0x65, 0xf4, 0x6b, 0xa3, 0x39, 0x8c, 0xe3, 0xc1, 0x6f, 0x0d, 0x6f, 0x58, 0x2b, 0x8a, 0xb5, 0xa2,
	0x78, 0xae, 0x68, 0x90, 0x92, 0xe0, 0x34, 0xfa, 0xfb, 0x16, 0x18, 0x69, 0x60, 0x34, 0x07, 0x46,
	0x83, 0x94, 0x8c, 0x4e, 0xa3, 0xeb, 0xc6, 0x87, 0xcb, 0x81, 0xd1, 0xf1, 0xf0, 0xf0, 0x1b, 0x50,
	0x38, 0xc3, 0x0a, 0xff, 0xd7, 0xf0, 0x6b, 0xb8, 0xdf, 0xd7, 0xb4, 0xfe, 0xad, 0xf0, 0x7e, 0x7f,
	0x90, 0x92, 0x7e, 0xff, 0x34, 0x4a, 0x57, 0xcd, 0x9d, 0xd9, 0xff, 0x3f, 0x00, 0x00, 0xff, 0xff,
	0x44, 0xb8, 0xfa, 0xb0, 0x9f, 0x07, 0x00, 0x00,
}

func (m *IbcRelay) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IbcRelay) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IbcRelay) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RawAction != nil {
		{
			size, err := m.RawAction.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintIbc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *FungibleTokenPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FungibleTokenPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FungibleTokenPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Memo) > 0 {
		i -= len(m.Memo)
		copy(dAtA[i:], m.Memo)
		i = encodeVarintIbc(dAtA, i, uint64(len(m.Memo)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintIbc(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintIbc(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintIbc(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintIbc(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Ics20Withdrawal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Ics20Withdrawal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Ics20Withdrawal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SourceChannel) > 0 {
		i -= len(m.SourceChannel)
		copy(dAtA[i:], m.SourceChannel)
		i = encodeVarintIbc(dAtA, i, uint64(len(m.SourceChannel)))
		i--
		dAtA[i] = 0x3a
	}
	if m.TimeoutTime != 0 {
		i = encodeVarintIbc(dAtA, i, uint64(m.TimeoutTime))
		i--
		dAtA[i] = 0x30
	}
	if m.TimeoutHeight != nil {
		{
			size, err := m.TimeoutHeight.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintIbc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.ReturnAddress != nil {
		{
			size, err := m.ReturnAddress.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintIbc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.DestinationChainAddress) > 0 {
		i -= len(m.DestinationChainAddress)
		copy(dAtA[i:], m.DestinationChainAddress)
		i = encodeVarintIbc(dAtA, i, uint64(len(m.DestinationChainAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Denom != nil {
		{
			size, err := m.Denom.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintIbc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Amount != nil {
		{
			size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintIbc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ClientData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClientData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClientData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProcessedHeight != 0 {
		i = encodeVarintIbc(dAtA, i, uint64(m.ProcessedHeight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ProcessedTime) > 0 {
		i -= len(m.ProcessedTime)
		copy(dAtA[i:], m.ProcessedTime)
		i = encodeVarintIbc(dAtA, i, uint64(len(m.ProcessedTime)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ClientState != nil {
		{
			size, err := m.ClientState.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintIbc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ClientId) > 0 {
		i -= len(m.ClientId)
		copy(dAtA[i:], m.ClientId)
		i = encodeVarintIbc(dAtA, i, uint64(len(m.ClientId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ClientCounter) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClientCounter) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClientCounter) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Counter != 0 {
		i = encodeVarintIbc(dAtA, i, uint64(m.Counter))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ConsensusState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConsensusState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConsensusState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ConsensusState != nil {
		{
			size, err := m.ConsensusState.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintIbc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VerifiedHeights) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VerifiedHeights) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VerifiedHeights) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Heights) > 0 {
		for iNdEx := len(m.Heights) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Heights[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintIbc(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ConnectionCounter) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConnectionCounter) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConnectionCounter) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Counter != 0 {
		i = encodeVarintIbc(dAtA, i, uint64(m.Counter))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ClientConnections) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClientConnections) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClientConnections) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Connections) > 0 {
		for iNdEx := len(m.Connections) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Connections[iNdEx])
			copy(dAtA[i:], m.Connections[iNdEx])
			i = encodeVarintIbc(dAtA, i, uint64(len(m.Connections[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *IbcParameters) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IbcParameters) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IbcParameters) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OutboundIcs20TransfersEnabled {
		i--
		if m.OutboundIcs20TransfersEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.InboundIcs20TransfersEnabled {
		i--
		if m.InboundIcs20TransfersEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.IbcEnabled {
		i--
		if m.IbcEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GenesisContent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisContent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisContent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IbcParams != nil {
		{
			size, err := m.IbcParams.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintIbc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintIbc(dAtA []byte, offset int, v uint64) int {
	offset -= sovIbc(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *IbcRelay) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RawAction != nil {
		l = m.RawAction.Size()
		n += 1 + l + sovIbc(uint64(l))
	}
	return n
}

func (m *FungibleTokenPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovIbc(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovIbc(uint64(l))
	}
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovIbc(uint64(l))
	}
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovIbc(uint64(l))
	}
	l = len(m.Memo)
	if l > 0 {
		n += 1 + l + sovIbc(uint64(l))
	}
	return n
}

func (m *Ics20Withdrawal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Amount != nil {
		l = m.Amount.Size()
		n += 1 + l + sovIbc(uint64(l))
	}
	if m.Denom != nil {
		l = m.Denom.Size()
		n += 1 + l + sovIbc(uint64(l))
	}
	l = len(m.DestinationChainAddress)
	if l > 0 {
		n += 1 + l + sovIbc(uint64(l))
	}
	if m.ReturnAddress != nil {
		l = m.ReturnAddress.Size()
		n += 1 + l + sovIbc(uint64(l))
	}
	if m.TimeoutHeight != nil {
		l = m.TimeoutHeight.Size()
		n += 1 + l + sovIbc(uint64(l))
	}
	if m.TimeoutTime != 0 {
		n += 1 + sovIbc(uint64(m.TimeoutTime))
	}
	l = len(m.SourceChannel)
	if l > 0 {
		n += 1 + l + sovIbc(uint64(l))
	}
	return n
}

func (m *ClientData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ClientId)
	if l > 0 {
		n += 1 + l + sovIbc(uint64(l))
	}
	if m.ClientState != nil {
		l = m.ClientState.Size()
		n += 1 + l + sovIbc(uint64(l))
	}
	l = len(m.ProcessedTime)
	if l > 0 {
		n += 1 + l + sovIbc(uint64(l))
	}
	if m.ProcessedHeight != 0 {
		n += 1 + sovIbc(uint64(m.ProcessedHeight))
	}
	return n
}

func (m *ClientCounter) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Counter != 0 {
		n += 1 + sovIbc(uint64(m.Counter))
	}
	return n
}

func (m *ConsensusState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ConsensusState != nil {
		l = m.ConsensusState.Size()
		n += 1 + l + sovIbc(uint64(l))
	}
	return n
}

func (m *VerifiedHeights) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Heights) > 0 {
		for _, e := range m.Heights {
			l = e.Size()
			n += 1 + l + sovIbc(uint64(l))
		}
	}
	return n
}

func (m *ConnectionCounter) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Counter != 0 {
		n += 1 + sovIbc(uint64(m.Counter))
	}
	return n
}

func (m *ClientConnections) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Connections) > 0 {
		for _, s := range m.Connections {
			l = len(s)
			n += 1 + l + sovIbc(uint64(l))
		}
	}
	return n
}

func (m *IbcParameters) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IbcEnabled {
		n += 2
	}
	if m.InboundIcs20TransfersEnabled {
		n += 2
	}
	if m.OutboundIcs20TransfersEnabled {
		n += 2
	}
	return n
}

func (m *GenesisContent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IbcParams != nil {
		l = m.IbcParams.Size()
		n += 1 + l + sovIbc(uint64(l))
	}
	return n
}

func sovIbc(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozIbc(x uint64) (n int) {
	return sovIbc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *IbcRelay) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIbc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IbcRelay: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IbcRelay: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawAction", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RawAction == nil {
				m.RawAction = &types.Any{}
			}
			if err := m.RawAction.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIbc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIbc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FungibleTokenPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIbc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FungibleTokenPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FungibleTokenPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIbc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIbc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Ics20Withdrawal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIbc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Ics20Withdrawal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Ics20Withdrawal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Amount == nil {
				m.Amount = &v1.Amount{}
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Denom == nil {
				m.Denom = &v11.Denom{}
			}
			if err := m.Denom.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationChainAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestinationChainAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReturnAddress", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ReturnAddress == nil {
				m.ReturnAddress = &v12.Address{}
			}
			if err := m.ReturnAddress.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TimeoutHeight == nil {
				m.TimeoutHeight = &types1.Height{}
			}
			if err := m.TimeoutHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutTime", wireType)
			}
			m.TimeoutTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeoutTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceChannel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceChannel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIbc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIbc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClientData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIbc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClientData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClientData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ClientState == nil {
				m.ClientState = &types.Any{}
			}
			if err := m.ClientState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProcessedTime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProcessedTime = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProcessedHeight", wireType)
			}
			m.ProcessedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProcessedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipIbc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIbc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClientCounter) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIbc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClientCounter: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClientCounter: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Counter", wireType)
			}
			m.Counter = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Counter |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipIbc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIbc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConsensusState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIbc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConsensusState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConsensusState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsensusState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ConsensusState == nil {
				m.ConsensusState = &types.Any{}
			}
			if err := m.ConsensusState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIbc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIbc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VerifiedHeights) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIbc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VerifiedHeights: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VerifiedHeights: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Heights", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Heights = append(m.Heights, &types1.Height{})
			if err := m.Heights[len(m.Heights)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIbc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIbc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConnectionCounter) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIbc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConnectionCounter: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConnectionCounter: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Counter", wireType)
			}
			m.Counter = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Counter |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipIbc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIbc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClientConnections) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIbc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClientConnections: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClientConnections: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Connections", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Connections = append(m.Connections, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIbc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIbc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IbcParameters) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIbc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IbcParameters: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IbcParameters: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IbcEnabled = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InboundIcs20TransfersEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.InboundIcs20TransfersEnabled = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutboundIcs20TransfersEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OutboundIcs20TransfersEnabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipIbc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIbc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisContent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIbc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisContent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisContent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.IbcParams == nil {
				m.IbcParams = &IbcParameters{}
			}
			if err := m.IbcParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIbc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIbc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipIbc(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowIbc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthIbc
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupIbc
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthIbc
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthIbc        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowIbc          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupIbc = fmt.Errorf("proto: unexpected end of group")
)
