// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: penumbra/core/component/distributions/v1/distributions.proto

package distributionsv1

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Distribution configuration data.
type DistributionsParameters struct {
	// The amount of staking token issued per block.
	StakingIssuancePerBlock uint64 `protobuf:"varint,1,opt,name=staking_issuance_per_block,json=stakingIssuancePerBlock,proto3" json:"staking_issuance_per_block,omitempty"`
}

func (m *DistributionsParameters) Reset()         { *m = DistributionsParameters{} }
func (m *DistributionsParameters) String() string { return proto.CompactTextString(m) }
func (*DistributionsParameters) ProtoMessage()    {}
func (*DistributionsParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e86d892e577363a, []int{0}
}
func (m *DistributionsParameters) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DistributionsParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DistributionsParameters.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DistributionsParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributionsParameters.Merge(m, src)
}
func (m *DistributionsParameters) XXX_Size() int {
	return m.Size()
}
func (m *DistributionsParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributionsParameters.DiscardUnknown(m)
}

var xxx_messageInfo_DistributionsParameters proto.InternalMessageInfo

func (m *DistributionsParameters) GetStakingIssuancePerBlock() uint64 {
	if m != nil {
		return m.StakingIssuancePerBlock
	}
	return 0
}

// Genesis data for the distributions module.
type GenesisContent struct {
	DistributionsParams *DistributionsParameters `protobuf:"bytes,1,opt,name=distributions_params,json=distributionsParams,proto3" json:"distributions_params,omitempty"`
}

func (m *GenesisContent) Reset()         { *m = GenesisContent{} }
func (m *GenesisContent) String() string { return proto.CompactTextString(m) }
func (*GenesisContent) ProtoMessage()    {}
func (*GenesisContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e86d892e577363a, []int{1}
}
func (m *GenesisContent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisContent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisContent.Merge(m, src)
}
func (m *GenesisContent) XXX_Size() int {
	return m.Size()
}
func (m *GenesisContent) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisContent.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisContent proto.InternalMessageInfo

func (m *GenesisContent) GetDistributionsParams() *DistributionsParameters {
	if m != nil {
		return m.DistributionsParams
	}
	return nil
}

func init() {
	proto.RegisterType((*DistributionsParameters)(nil), "penumbra.core.component.distributions.v1.DistributionsParameters")
	proto.RegisterType((*GenesisContent)(nil), "penumbra.core.component.distributions.v1.GenesisContent")
}

func init() {
	proto.RegisterFile("penumbra/core/component/distributions/v1/distributions.proto", fileDescriptor_3e86d892e577363a)
}

var fileDescriptor_3e86d892e577363a = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x31, 0x8a, 0xdb, 0x40,
	0x14, 0x86, 0x2d, 0xc5, 0xa4, 0x50, 0x20, 0x85, 0x12, 0x70, 0x48, 0x21, 0x82, 0x2b, 0x17, 0x8e,
	0x06, 0x25, 0x29, 0x82, 0x9c, 0x26, 0x92, 0xc1, 0xa4, 0x08, 0x08, 0x17, 0x2a, 0x82, 0x40, 0x8c,
	0xe4, 0x87, 0x3d, 0xd8, 0x9a, 0x11, 0x33, 0x4f, 0x3a, 0x42, 0xea, 0xe4, 0x0a, 0x29, 0x73, 0x92,
	0x65, 0x2b, 0x97, 0x5b, 0x2e, 0x72, 0xb7, 0xa7, 0x58, 0xc6, 0xd8, 0xde, 0x1d, 0x96, 0x05, 0x35,
	0x12, 0x7a, 0xef, 0xfb, 0xf4, 0xff, 0x48, 0xe3, 0x7c, 0xab, 0x81, 0x37, 0x55, 0x21, 0x29, 0x29,
	0x85, 0x04, 0x52, 0x8a, 0xaa, 0x16, 0x1c, 0x38, 0x92, 0x15, 0x53, 0x28, 0x59, 0xd1, 0x20, 0x13,
	0x5c, 0x91, 0x36, 0x30, 0x07, 0x7e, 0x2d, 0x05, 0x0a, 0x77, 0x72, 0xb6, 0x7d, 0x6d, 0xfb, 0x17,
	0xdb, 0x37, 0xe1, 0x36, 0x18, 0xa7, 0xce, 0x68, 0xfe, 0x78, 0x96, 0x50, 0x49, 0x2b, 0x40, 0x90,
	0xca, 0x9d, 0x39, 0xef, 0x15, 0xd2, 0x2d, 0xe3, 0xeb, 0x9c, 0x29, 0xd5, 0x50, 0x5e, 0x42, 0x5e,
	0x83, 0xcc, 0x8b, 0x9d, 0x28, 0xb7, 0xef, 0xac, 0x0f, 0xd6, 0x64, 0xb8, 0x1c, 0x9d, 0x88, 0x1f,
	0x27, 0x20, 0x01, 0x19, 0xe9, 0xf5, 0xf8, 0xb7, 0xe5, 0xbc, 0x5e, 0x00, 0x07, 0xc5, 0x54, 0x2c,
	0x38, 0x02, 0x47, 0x17, 0x9d, 0xb7, 0x46, 0x7c, 0x5e, 0xeb, 0x2c, 0x75, 0x7c, 0xd3, 0xab, 0x4f,
	0xdf, 0xfd, 0xbe, 0x9d, 0xfd, 0x67, 0x0a, 0x2f, 0xdf, 0xac, 0x9e, 0x2c, 0x54, 0xf4, 0xf7, 0xc5,
	0x55, 0xe7, 0x59, 0xfb, 0xce, 0xb3, 0x6e, 0x3b, 0xcf, 0xfa, 0x73, 0xf0, 0x06, 0xfb, 0x83, 0x37,
	0xb8, 0x39, 0x78, 0x03, 0x67, 0x5a, 0x8a, 0xaa, 0x77, 0x6a, 0xe4, 0x9a, 0xb1, 0xfa, 0x3b, 0x27,
	0xd6, 0xaf, 0x7a, 0xcd, 0x70, 0xd3, 0x14, 0x5a, 0x24, 0x0a, 0x25, 0xe5, 0x6b, 0xd8, 0x89, 0x16,
	0x3e, 0xb6, 0xc0, 0xb1, 0x91, 0xa0, 0x08, 0xe3, 0x08, 0xb2, 0xdc, 0x50, 0x7d, 0x57, 0x48, 0xda,
	0xaf, 0xe4, 0xf8, 0x40, 0xfa, 0xfe, 0xdf, 0x99, 0x31, 0x68, 0x83, 0x7f, 0xf6, 0x30, 0x89, 0xe3,
	0xf9, 0x7f, 0x7b, 0x92, 0x9c, 0x9b, 0xc7, 0xba, 0x79, 0x7c, 0x69, 0x6e, 0xf4, 0xf4, 0xd3, 0xe0,
	0xfa, 0x01, 0xcd, 0x34, 0x9a, 0x5d, 0xd0, 0xcc, 0x40, 0xb3, 0x34, 0xe8, 0xec, 0x2f, 0x7d, 0xd1,
	0x6c, 0x91, 0x44, 0x3f, 0x01, 0xe9, 0x8a, 0x22, 0xbd, 0xb3, 0xa7, 0x67, 0x2d, 0x0c, 0xb5, 0xa7,
	0xaf, 0x27, 0x31, 0x0c, 0x0d, 0x33, 0x0c, 0xd3, 0xa0, 0x78, 0x79, 0x3c, 0xa5, 0x9f, 0xef, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x28, 0x0c, 0x96, 0x3c, 0xe5, 0x02, 0x00, 0x00,
}

func (m *DistributionsParameters) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DistributionsParameters) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DistributionsParameters) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.StakingIssuancePerBlock != 0 {
		i = encodeVarintDistributions(dAtA, i, uint64(m.StakingIssuancePerBlock))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GenesisContent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisContent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisContent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DistributionsParams != nil {
		{
			size, err := m.DistributionsParams.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDistributions(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDistributions(dAtA []byte, offset int, v uint64) int {
	offset -= sovDistributions(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DistributionsParameters) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StakingIssuancePerBlock != 0 {
		n += 1 + sovDistributions(uint64(m.StakingIssuancePerBlock))
	}
	return n
}

func (m *GenesisContent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DistributionsParams != nil {
		l = m.DistributionsParams.Size()
		n += 1 + l + sovDistributions(uint64(l))
	}
	return n
}

func sovDistributions(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDistributions(x uint64) (n int) {
	return sovDistributions(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DistributionsParameters) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDistributions
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DistributionsParameters: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DistributionsParameters: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakingIssuancePerBlock", wireType)
			}
			m.StakingIssuancePerBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StakingIssuancePerBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDistributions(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDistributions
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisContent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDistributions
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisContent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisContent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributionsParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDistributions
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDistributions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DistributionsParams == nil {
				m.DistributionsParams = &DistributionsParameters{}
			}
			if err := m.DistributionsParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDistributions(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDistributions
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDistributions(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDistributions
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDistributions
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDistributions
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDistributions
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDistributions
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDistributions
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDistributions        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDistributions          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDistributions = fmt.Errorf("proto: unexpected end of group")
)
