// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: penumbra/core/component/dao/v1alpha1/dao.proto

package daov1alpha1

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Dao parameter data.
type DaoParameters struct {
	// Whether DAO spend proposals are enabled.
	DaoSpendProposalsEnabled bool `protobuf:"varint,1,opt,name=dao_spend_proposals_enabled,json=daoSpendProposalsEnabled,proto3" json:"dao_spend_proposals_enabled,omitempty"`
}

func (m *DaoParameters) Reset()         { *m = DaoParameters{} }
func (m *DaoParameters) String() string { return proto.CompactTextString(m) }
func (*DaoParameters) ProtoMessage()    {}
func (*DaoParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2476c8b34dca79f, []int{0}
}
func (m *DaoParameters) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DaoParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DaoParameters.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DaoParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DaoParameters.Merge(m, src)
}
func (m *DaoParameters) XXX_Size() int {
	return m.Size()
}
func (m *DaoParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_DaoParameters.DiscardUnknown(m)
}

var xxx_messageInfo_DaoParameters proto.InternalMessageInfo

func (m *DaoParameters) GetDaoSpendProposalsEnabled() bool {
	if m != nil {
		return m.DaoSpendProposalsEnabled
	}
	return false
}

// Dao genesis state.
type GenesisContent struct {
	// Dao parameters.
	DaoParams *DaoParameters `protobuf:"bytes,1,opt,name=dao_params,json=daoParams,proto3" json:"dao_params,omitempty"`
}

func (m *GenesisContent) Reset()         { *m = GenesisContent{} }
func (m *GenesisContent) String() string { return proto.CompactTextString(m) }
func (*GenesisContent) ProtoMessage()    {}
func (*GenesisContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2476c8b34dca79f, []int{1}
}
func (m *GenesisContent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisContent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisContent.Merge(m, src)
}
func (m *GenesisContent) XXX_Size() int {
	return m.Size()
}
func (m *GenesisContent) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisContent.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisContent proto.InternalMessageInfo

func (m *GenesisContent) GetDaoParams() *DaoParameters {
	if m != nil {
		return m.DaoParams
	}
	return nil
}

func init() {
	proto.RegisterType((*DaoParameters)(nil), "penumbra.core.component.dao.v1alpha1.DaoParameters")
	proto.RegisterType((*GenesisContent)(nil), "penumbra.core.component.dao.v1alpha1.GenesisContent")
}

func init() {
	proto.RegisterFile("penumbra/core/component/dao/v1alpha1/dao.proto", fileDescriptor_a2476c8b34dca79f)
}

var fileDescriptor_a2476c8b34dca79f = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0xd2, 0x31, 0xcb, 0xd3, 0x40,
	0x18, 0x07, 0xf0, 0x26, 0x88, 0xd4, 0x88, 0x0e, 0x9d, 0x0a, 0x42, 0x90, 0xd2, 0xa1, 0x8b, 0x77,
	0xd6, 0x2e, 0x12, 0x71, 0x69, 0x22, 0x9d, 0x94, 0x50, 0xc1, 0x41, 0x02, 0xe5, 0x49, 0xee, 0xa1,
	0x29, 0x24, 0xf7, 0x1c, 0x77, 0xd7, 0x7c, 0x0e, 0x3f, 0x83, 0xa3, 0x9f, 0x44, 0x9c, 0x3a, 0x3a,
	0x4a, 0xba, 0xe9, 0x97, 0x90, 0xeb, 0xdb, 0xeb, 0xcb, 0xbb, 0x65, 0x49, 0xf2, 0x90, 0xdf, 0xff,
	0xc9, 0x9f, 0x24, 0x11, 0x53, 0x28, 0x8f, 0x6d, 0xa9, 0x81, 0x57, 0xa4, 0x91, 0x57, 0xd4, 0x2a,
	0x92, 0x28, 0x2d, 0x17, 0x40, 0xbc, 0x5b, 0x42, 0xa3, 0x6a, 0x58, 0xba, 0x81, 0x29, 0x4d, 0x96,
	0x26, 0x73, 0xef, 0x99, 0xf3, 0xec, 0xe6, 0x99, 0x23, 0xde, 0xcf, 0x3e, 0x45, 0xcf, 0x32, 0xa0,
	0x1c, 0x34, 0xb4, 0x68, 0x51, 0x9b, 0xc9, 0xfb, 0xe8, 0x85, 0x00, 0xda, 0x19, 0x85, 0x52, 0xec,
	0x94, 0x26, 0x45, 0x06, 0x1a, 0xb3, 0x43, 0x09, 0x65, 0x83, 0x62, 0x1a, 0xbc, 0x0c, 0x16, 0xe3,
	0xed, 0x54, 0x00, 0x7d, 0x76, 0x22, 0xf7, 0xe0, 0xc3, 0xdd, 0xfd, 0x99, 0x88, 0x9e, 0x6f, 0x50,
	0xa2, 0x39, 0x98, 0x94, 0xa4, 0x45, 0x69, 0x27, 0xdb, 0x28, 0x72, 0x0b, 0x95, 0x7b, 0x84, 0xb9,
	0xe4, 0x9f, 0xbe, 0x59, 0xb1, 0x21, 0xe5, 0xd8, 0x83, 0x66, 0xdb, 0x27, 0xe2, 0x3a, 0x9a, 0xf5,
	0xbf, 0xf0, 0x67, 0x1f, 0x07, 0xa7, 0x3e, 0x0e, 0xfe, 0xf4, 0x71, 0xf0, 0xed, 0x1c, 0x8f, 0x4e,
	0xe7, 0x78, 0xf4, 0xfb, 0x1c, 0x8f, 0xa2, 0x45, 0x45, 0xed, 0xa0, 0xed, 0xeb, 0xb1, 0x5b, 0xef,
	0x5e, 0x55, 0x1e, 0x7c, 0xad, 0xf7, 0x07, 0x5b, 0x1f, 0x4b, 0x47, 0xb9, 0xb1, 0x1a, 0xe4, 0x1e,
	0x1b, 0xea, 0xf0, 0x55, 0x87, 0xd2, 0x1e, 0x35, 0x1a, 0x7e, 0x90, 0x16, 0x75, 0x55, 0x83, 0x3b,
	0x1b, 0xcb, 0xbb, 0xb7, 0xfc, 0x32, 0xf0, 0x21, 0x1f, 0xe5, 0x9d, 0x00, 0xf2, 0xd7, 0xdf, 0xc3,
	0x47, 0x79, 0x9a, 0x66, 0x3f, 0xc2, 0x79, 0xee, 0x3b, 0xa6, 0xae, 0x63, 0x7a, 0xeb, 0x98, 0x01,
	0xb1, 0x2f, 0x57, 0xfd, 0xeb, 0x9e, 0x15, 0x8e, 0x15, 0x37, 0x56, 0x64, 0x40, 0x85, 0x67, 0x7d,
	0xf8, 0x7a, 0x08, 0x2b, 0x36, 0xf9, 0xfa, 0x23, 0x5a, 0x10, 0x60, 0xe1, 0x6f, 0xb8, 0xf0, 0x91,
	0x24, 0x71, 0x19, 0x77, 0xbc, 0x86, 0x92, 0x24, 0x03, 0x4a, 0x12, 0x1f, 0x2b, 0x1f, 0x5f, 0x7e,
	0xa8, 0xd5, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x03, 0x75, 0x7e, 0x4f, 0x82, 0x02, 0x00, 0x00,
}

func (m *DaoParameters) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DaoParameters) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DaoParameters) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DaoSpendProposalsEnabled {
		i--
		if m.DaoSpendProposalsEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GenesisContent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisContent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisContent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DaoParams != nil {
		{
			size, err := m.DaoParams.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDao(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDao(dAtA []byte, offset int, v uint64) int {
	offset -= sovDao(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DaoParameters) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DaoSpendProposalsEnabled {
		n += 2
	}
	return n
}

func (m *GenesisContent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DaoParams != nil {
		l = m.DaoParams.Size()
		n += 1 + l + sovDao(uint64(l))
	}
	return n
}

func sovDao(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDao(x uint64) (n int) {
	return sovDao(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DaoParameters) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDao
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DaoParameters: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DaoParameters: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DaoSpendProposalsEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDao
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DaoSpendProposalsEnabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipDao(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDao
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisContent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDao
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisContent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisContent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DaoParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDao
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDao
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDao
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DaoParams == nil {
				m.DaoParams = &DaoParameters{}
			}
			if err := m.DaoParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDao(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDao
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDao(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDao
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDao
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDao
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDao
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDao
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDao
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDao        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDao          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDao = fmt.Errorf("proto: unexpected end of group")
)
