// Code generated by "stringer -type=Capability"; DO NOT EDIT.

package relayer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TimestampTimeout-0]
	_ = x[HeightTimeout-1]
	_ = x[Flush-2]
}

const _Capability_name = "TimestampTimeoutHeightTimeoutFlush"

var _Capability_index = [...]uint8{0, 16, 29, 34}

func (i Capability) String() string {
	if i < 0 || i >= Capability(len(_Capability_index)-1) {
		return "Capability(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Capability_name[_Capability_index[i]:_Capability_index[i+1]]
}
