// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: penumbra/crypto/decaf377_rdsa/v1/decaf377_rdsa.proto

package decaf377_rdsav1

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SpendAuthSignature struct {
	Inner []byte `protobuf:"bytes,1,opt,name=inner,proto3" json:"inner,omitempty"`
}

func (m *SpendAuthSignature) Reset()         { *m = SpendAuthSignature{} }
func (m *SpendAuthSignature) String() string { return proto.CompactTextString(m) }
func (*SpendAuthSignature) ProtoMessage()    {}
func (*SpendAuthSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_70f2e93711fd8093, []int{0}
}
func (m *SpendAuthSignature) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SpendAuthSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SpendAuthSignature.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SpendAuthSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpendAuthSignature.Merge(m, src)
}
func (m *SpendAuthSignature) XXX_Size() int {
	return m.Size()
}
func (m *SpendAuthSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_SpendAuthSignature.DiscardUnknown(m)
}

var xxx_messageInfo_SpendAuthSignature proto.InternalMessageInfo

func (m *SpendAuthSignature) GetInner() []byte {
	if m != nil {
		return m.Inner
	}
	return nil
}

type BindingSignature struct {
	Inner []byte `protobuf:"bytes,1,opt,name=inner,proto3" json:"inner,omitempty"`
}

func (m *BindingSignature) Reset()         { *m = BindingSignature{} }
func (m *BindingSignature) String() string { return proto.CompactTextString(m) }
func (*BindingSignature) ProtoMessage()    {}
func (*BindingSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_70f2e93711fd8093, []int{1}
}
func (m *BindingSignature) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BindingSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BindingSignature.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BindingSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindingSignature.Merge(m, src)
}
func (m *BindingSignature) XXX_Size() int {
	return m.Size()
}
func (m *BindingSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_BindingSignature.DiscardUnknown(m)
}

var xxx_messageInfo_BindingSignature proto.InternalMessageInfo

func (m *BindingSignature) GetInner() []byte {
	if m != nil {
		return m.Inner
	}
	return nil
}

type SpendVerificationKey struct {
	Inner []byte `protobuf:"bytes,1,opt,name=inner,proto3" json:"inner,omitempty"`
}

func (m *SpendVerificationKey) Reset()         { *m = SpendVerificationKey{} }
func (m *SpendVerificationKey) String() string { return proto.CompactTextString(m) }
func (*SpendVerificationKey) ProtoMessage()    {}
func (*SpendVerificationKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_70f2e93711fd8093, []int{2}
}
func (m *SpendVerificationKey) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SpendVerificationKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SpendVerificationKey.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SpendVerificationKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpendVerificationKey.Merge(m, src)
}
func (m *SpendVerificationKey) XXX_Size() int {
	return m.Size()
}
func (m *SpendVerificationKey) XXX_DiscardUnknown() {
	xxx_messageInfo_SpendVerificationKey.DiscardUnknown(m)
}

var xxx_messageInfo_SpendVerificationKey proto.InternalMessageInfo

func (m *SpendVerificationKey) GetInner() []byte {
	if m != nil {
		return m.Inner
	}
	return nil
}

func init() {
	proto.RegisterType((*SpendAuthSignature)(nil), "penumbra.crypto.decaf377_rdsa.v1.SpendAuthSignature")
	proto.RegisterType((*BindingSignature)(nil), "penumbra.crypto.decaf377_rdsa.v1.BindingSignature")
	proto.RegisterType((*SpendVerificationKey)(nil), "penumbra.crypto.decaf377_rdsa.v1.SpendVerificationKey")
}

func init() {
	proto.RegisterFile("penumbra/crypto/decaf377_rdsa/v1/decaf377_rdsa.proto", fileDescriptor_70f2e93711fd8093)
}

var fileDescriptor_70f2e93711fd8093 = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0xd2, 0xbf, 0x4b, 0xc3, 0x40,
	0x14, 0x07, 0xf0, 0x26, 0xa2, 0x43, 0x70, 0xd0, 0xd2, 0xc1, 0x29, 0x96, 0xe2, 0x50, 0xfc, 0x91,
	0x23, 0x54, 0xa8, 0xc4, 0xc9, 0xb4, 0xe0, 0x20, 0x42, 0x68, 0x21, 0x83, 0x04, 0xe4, 0x7a, 0xf7,
	0x9a, 0x1c, 0xd8, 0xbb, 0x70, 0xb9, 0x1c, 0xf4, 0xbf, 0xf0, 0x6f, 0x70, 0xf4, 0x2f, 0x11, 0xa7,
	0x8e, 0xe2, 0x24, 0xe9, 0xe6, 0x5f, 0x21, 0x6d, 0x2c, 0x36, 0x20, 0x64, 0x3a, 0xde, 0xe3, 0xf3,
	0x8e, 0xef, 0x3b, 0xce, 0xba, 0x4c, 0x81, 0xe7, 0xb3, 0x89, 0xc4, 0x88, 0xc8, 0x79, 0xaa, 0x04,
	0xa2, 0x40, 0xf0, 0xb4, 0xd7, 0xef, 0x3f, 0x4a, 0x9a, 0x61, 0xa4, 0xdd, 0x6a, 0xc3, 0x49, 0xa5,
	0x50, 0xa2, 0xd9, 0xde, 0x4c, 0x39, 0xe5, 0x94, 0x53, 0x45, 0xda, 0xed, 0x9c, 0x5a, 0xcd, 0x71,
	0x0a, 0x9c, 0xde, 0xe4, 0x2a, 0x19, 0xb3, 0x98, 0x63, 0x95, 0x4b, 0x68, 0xb6, 0xac, 0x5d, 0xc6,
	0x39, 0xc8, 0x23, 0xa3, 0x6d, 0x74, 0xf7, 0x47, 0x65, 0xd1, 0xe9, 0x5a, 0x07, 0x3e, 0xe3, 0x94,
	0xf1, 0xb8, 0x4e, 0x9e, 0x5b, 0xad, 0xf5, 0xad, 0x21, 0x48, 0x36, 0x65, 0x04, 0x2b, 0x26, 0xf8,
	0x1d, 0xcc, 0xff, 0xd7, 0xfe, 0xa7, 0xf9, 0x56, 0xd8, 0xc6, 0xa2, 0xb0, 0x8d, 0xaf, 0xc2, 0x36,
	0x9e, 0x97, 0x76, 0x63, 0xb1, 0xb4, 0x1b, 0x1f, 0x4b, 0xbb, 0x61, 0x9d, 0x10, 0x31, 0x73, 0xea,
	0x96, 0xf0, 0x0f, 0x87, 0xbf, 0x9d, 0x11, 0xcd, 0x70, 0xb0, 0xda, 0x3c, 0x30, 0x1e, 0x92, 0x98,
	0xa9, 0x24, 0x9f, 0x38, 0x44, 0xcc, 0x50, 0xa6, 0x24, 0xe6, 0x31, 0x3c, 0x09, 0x0d, 0x17, 0x1a,
	0xf8, 0x2a, 0x79, 0x86, 0x18, 0x57, 0x20, 0x49, 0x82, 0x57, 0x67, 0xa6, 0x90, 0xbe, 0x42, 0xeb,
	0x02, 0xd5, 0xbd, 0xf4, 0x75, 0xa5, 0xa1, 0xdd, 0x17, 0x73, 0x27, 0x18, 0x0c, 0x5f, 0xcd, 0xe3,
	0x60, 0x93, 0x73, 0x50, 0xe6, 0xdc, 0x4e, 0xe5, 0x84, 0xee, 0xfb, 0x9f, 0x88, 0x4a, 0x11, 0x6d,
	0x8b, 0x28, 0x74, 0x0b, 0xf3, 0xac, 0x46, 0x44, 0xb7, 0x81, 0x7f, 0x0f, 0x0a, 0x53, 0xac, 0xf0,
	0xb7, 0xd9, 0xd9, 0x68, 0xcf, 0x2b, 0xb9, 0xe7, 0x6d, 0x7b, 0xcf, 0x0b, 0xdd, 0xc9, 0xde, 0xfa,
	0x27, 0xf4, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xab, 0x14, 0x0d, 0x16, 0x41, 0x02, 0x00, 0x00,
}

func (m *SpendAuthSignature) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SpendAuthSignature) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SpendAuthSignature) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Inner) > 0 {
		i -= len(m.Inner)
		copy(dAtA[i:], m.Inner)
		i = encodeVarintDecaf377Rdsa(dAtA, i, uint64(len(m.Inner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *BindingSignature) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BindingSignature) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BindingSignature) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Inner) > 0 {
		i -= len(m.Inner)
		copy(dAtA[i:], m.Inner)
		i = encodeVarintDecaf377Rdsa(dAtA, i, uint64(len(m.Inner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SpendVerificationKey) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SpendVerificationKey) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SpendVerificationKey) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Inner) > 0 {
		i -= len(m.Inner)
		copy(dAtA[i:], m.Inner)
		i = encodeVarintDecaf377Rdsa(dAtA, i, uint64(len(m.Inner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDecaf377Rdsa(dAtA []byte, offset int, v uint64) int {
	offset -= sovDecaf377Rdsa(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SpendAuthSignature) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Inner)
	if l > 0 {
		n += 1 + l + sovDecaf377Rdsa(uint64(l))
	}
	return n
}

func (m *BindingSignature) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Inner)
	if l > 0 {
		n += 1 + l + sovDecaf377Rdsa(uint64(l))
	}
	return n
}

func (m *SpendVerificationKey) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Inner)
	if l > 0 {
		n += 1 + l + sovDecaf377Rdsa(uint64(l))
	}
	return n
}

func sovDecaf377Rdsa(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDecaf377Rdsa(x uint64) (n int) {
	return sovDecaf377Rdsa(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SpendAuthSignature) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDecaf377Rdsa
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SpendAuthSignature: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SpendAuthSignature: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inner", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDecaf377Rdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDecaf377Rdsa
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDecaf377Rdsa
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Inner = append(m.Inner[:0], dAtA[iNdEx:postIndex]...)
			if m.Inner == nil {
				m.Inner = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDecaf377Rdsa(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDecaf377Rdsa
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BindingSignature) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDecaf377Rdsa
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BindingSignature: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BindingSignature: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inner", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDecaf377Rdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDecaf377Rdsa
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDecaf377Rdsa
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Inner = append(m.Inner[:0], dAtA[iNdEx:postIndex]...)
			if m.Inner == nil {
				m.Inner = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDecaf377Rdsa(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDecaf377Rdsa
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SpendVerificationKey) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDecaf377Rdsa
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SpendVerificationKey: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SpendVerificationKey: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inner", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDecaf377Rdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDecaf377Rdsa
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDecaf377Rdsa
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Inner = append(m.Inner[:0], dAtA[iNdEx:postIndex]...)
			if m.Inner == nil {
				m.Inner = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDecaf377Rdsa(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDecaf377Rdsa
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDecaf377Rdsa(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDecaf377Rdsa
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDecaf377Rdsa
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDecaf377Rdsa
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDecaf377Rdsa
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDecaf377Rdsa
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDecaf377Rdsa
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDecaf377Rdsa        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDecaf377Rdsa          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDecaf377Rdsa = fmt.Errorf("proto: unexpected end of group")
)
